mypoll/mypoll/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('newpoll/', include('newpoll.urls')),
    path('admin/', admin.site.urls),
]

mypoll/newpoll/urls.py
from django.urls import path

from . import views
app_name='newpoll'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /newpoll/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /newpoll/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mypoll/newpoll/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
# Create your models here.

mypoll/newpoll/views.py
from django.http import Http404
from django.http import HttpResponse
from django.template import loader
from .models import Choice,Question
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('newpoll/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'newpoll/detail.html', {'question': question})
    # return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'newpoll/results.html', {'question': question})
    # return HttpResponse(response % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'newpoll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('newpoll:results', args=(question.id,)))
# Create your views here.

mypoll/newpoll/templates/newpoll/detail.html
<form action="{% url 'newpoll:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

mypoll/newpoll/templates/newpoll/index.html
<nav>
    <div class="navbar">
        <i class="bx bx-menu"></i>
        <div class="logo"><a href="#">POLLS APP</a></div>
        <div class="nav-links">
            <div class="sidebar-logo">
            <span class="logo_name">POLLS APP</span>
            <i class="bx bx-x"></i>
            </div>
            <ul class="links">
            <li><a href="#">Home</a></li>
            <li><a href="#">Create</a></li>
            </ul>
        </div>
        <!-- <div class="search-box">
          <i class="bx bx-search"></i>
          <div class="input-box">
            <input type="text" placeholder="Search">
          </div>
      </div> -->
    </div>
</nav>
{% if latest_question_list %}
    <ul>
    <div class="dis">
    {% for question in latest_question_list %}
        <div class="card">
            <div class="cont">
                <li><a href="/newpoll/{{ question.id }}/">{{ question.question_text }}</a></li> 
            </div>
        </div>
    {% endfor %}
    </div>
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% load static %}

<link rel="stylesheet" href="/static/newpoll/style.css?{%now "U" %}"/>
<!-- <link rel="stylesheet" href="/static/css/mycss.css?{% now "U" %}"/> -->

mypoll/newpoll/templates/newpoll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'newpoll:detail' question.id %}">Vote again?</a>

mypoll/newpoll/templates/newpoll/vote.html
{{question}}